### PR TITLE
Merge pull request #1 from robertnorrie/patch-1

### PR DESCRIPTION
**Pull request by robertnorrie**
The link to the setup.md file was broken. Here is a fix!

### CODE REVIEW

**Review by gm3dmo — APPROVED** [review]

**Comment by Sebastianoskiojoj** [comment]
142718e2c117132ee1da2bfb2d415fd604067294

**Comment by Sebastianoskiojoj** [comment]
> The link to the setup.md file was broken. Here is a fix!

**Review by Sebastianoskiojoj — COMMENTED** [review]
get-a-team-by-name.sh

**Comment by Sebastianoskiojoj** [comment]
539f0111b638ccd69db1253cb8f0de1137b67918

**Pull request merged**
