### PR TITLE
Add scripts for mobile GHES testing

### PR DESCRIPTION
**Pull request by iskae**

### CODE REVIEW

**Comment by gm3dmo** [comment]
@iskae would it be easier if we add `has_discussions` as a default for the test repository?

**Comment by iskae** [comment]
@gm3dmo absolutely 💯 Just was trying some things for the passion week project 😂 Lets default to discussion enabled for testing purposes 🙇

**Comment by gm3dmo** [comment]
Cool. Discussions now default to true in the create-repo-testrepo.sh script.

**Comment by iskae** [comment]
Oh nice 🎉 I was about to update this PR to reflect that change, but you were waaay faster than me 🤣 

Thanks a bunch 🙇

**Comment by gm3dmo** [comment]
https://github.com/gm3dmo/the-power/issues/108 I've raised this so that we can push them out to nice configurables in the script. They will default to true.

**Comment by iskae** [comment]
Closing this PR and moving this script to the mobile repo 🙇

**Pull request closed without merging**
